Print a newline in pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,4 +1,7 @@
 #!/bin/sh
 
 bunx fast-staged
+
+EXIT_CODE=$? # save exit code from fast-staged that gets overwritten by echo
 echo # print a newline
+exit $EXIT_CODE
